### ISSUE TITLE
Identify open data sources

### ISSUE THREAD

**Issue by ghost** [callysto/hackathon#27]
Pick a dataset associated to the topic you are interested in. 

We have compiled a list to get you started. (See table below). 

You are welcome to suggest a different dataset. If you are working with a different dataset, please include a link to the dataset in the comments, along with a license to the dataset. **Please ensure you select open datasets**.

Data set compilation as of Oct 16 2020 (adding to the table as people comment here).

| Main Topic | Subtopic | Link to data | License |
| -  | - | - | - |
|Climate change and data| CO2 emissions |[World Bank climate change data](https://data.worldbank.org/topic/climate-change?end=2018&start=2001) |[open data](https://data.worldbank.org/topic/climate-change?end=2018&start=2001) |
|Climate change and data| Trends in temperatures |[monthly temperature readings at canadian sites](https://www.canada.ca/en/environment-climate-change/services/climate-change/science-research-data/climate-trends-variability/adjusted-homogenized-canadian-data/surface-air-temperature-access.html) |[Open Government Licence - Canada](https://open.canada.ca/en/open-government-licence-canada) |
|Climate change and data| Trends in human behaviour (pre and post industrial revolution | [Hyde](https://themasites.pbl.nl/tridion/en/themasites/hyde/index.html) site [data](https://dataportaal.pbl.nl/downloads/HYDE/)[1] |[creative commons 3.0](https://creativecommons.org/licenses/by/3.0/) |
|Ocean monitoring | Impact of (micro)plastics on marine wildlife | [Hudson River Herring Stomach Contents](https://data.mendeley.com/datasets/s45rhrs5cf/1)[2] | [creative commons 4.0](https://creativecommons.org/licenses/by/4.0/) |
|Ocean monitoring | Impact of industrial fishing practices on marine wildlife | [Alaska Sea Shelf Groundfish Trawl Survey](https://www.fisheries.noaa.gov/resource/data/1982-2018-northern-bering-sea-shelf-groundfish-bottom-trawl-survey-data) | [open for non-commercial, scientific and educational uses](https://www.fisheries.noaa.gov/website-policies-and-disclaimers#copyright-policy) |
|Ocean monitoring | Changes in population size, behavioural patterns of a given species | [grey reef shark movements](http://oceantrackingnetwork.org/trackathon/data-sets/) | [open - but must inform OTN of data products created](https://members.oceantrack.org/data/policies/) |
|Citizen participation | Demographics of voters, involvement trends | [Electoral Districts for the 2015 AB election](https://open.alberta.ca/dataset/alberta-provincial-electoral-division-profiles-2010-boundaries-2016-census-data) and [2016 Census information](https://open.alberta.ca/opendata/2015-general-election-results) | Open Government Licence - Alberta |
|Citizen participation | Visualizing and interpreting data on budget and expenses | [Federal Budget Data Sets](https://open.canada.ca/data/en/dataset/a35cf382-690c-4221-a971-cf0fd189a46f)| Open Government Licence - Canada |
|Citizen participation | Public involvement in policy | [2018 BC Election Referendum Results](https://catalogue.data.gov.bc.ca/dataset/2018-referendum-voting-results)  | Elections BC Open Data Licence |
|Socio economic status and life quality | COVID-19 impact in marginalized groups |[Canadian Confirmed Case details](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310078101)  and [Perspectives on COVID-19: Impacts on underrepresented populations](https://www.sshrc-crsh.gc.ca/news_room-salle_de_presse/perspectives/covid-19/underrepresented_communities-communautes_sous-representees-eng.aspx)| Open Government Licence - Canada |
|Socio economic status and life quality | Income and educational attainment | [Labour market outcomes of post secondary graduates](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3710018801&pickMembers%5B0%5D=1.1&pickMembers%5B1%5D=4.1&pickMembers%5B2%5D=5.1) | Open Government Licence - Canada |
|Socio economic status and life quality | Income and health outcomes | [World Bank Open Data](https://data.worldbank.org) | Open Data |
|Socio economic status and life quality | Geographic distribution of access to services like education and internet in Canada | [National Broadband Data](https://open.canada.ca/data/en/dataset/00a331db-121b-445d-b119-35dbbe3eedd9)| Open Government Licence - Canada |

[1]: There is an incredible amount of datasets available at this link. This [global summary]( https://swift-yeg.cloud.cybera.ca:8080/v1/AUTH_233e84cd313945c992b4b585f7b9125d/callysto-open-data/anthromes_summary.txt) and [table]( https://swift-yeg.cloud.cybera.ca:8080/v1/AUTH_233e84cd313945c992b4b585f7b9125d/callysto-open-data/Table1_Ellis_Beusen_Goldewijk.png) of codes. If you decide to use the data sorted by country then be sure to reference these [ISO codes](https://swift-yeg.cloud.cybera.ca:8080/v1/AUTH_233e84cd313945c992b4b585f7b9125d/callysto-open-data/HYDE_country_codes.csv).
[2]: The data presented is a bit messy and in .xlxs format. The raw data can be found [here]( https://swift-yeg.cloud.cybera.ca:8080/v1/AUTH_233e84cd313945c992b4b585f7b9125d/callysto-open-data/Hudson_River_fish_data.csv) as a csv. But the link in the above table will explain the codes.

**Comment by BryceHaley** [comment]
Here are some more datasets:

| Main Topic | Subtopic | Link to data | License |
| -  | - | - | - |
|Climate change and data| CO2 emissions |[world bank climate change data](https://data.worldbank.org/topic/climate-change?end=2018&start=2001) |[open data](https://data.worldbank.org/topic/climate-change?end=2018&start=2001) |
|Climate change and data| Trends in temperatures |[monthly temperature readings at canadian sites](https://www.canada.ca/en/environment-climate-change/services/climate-change/science-research-data/climate-trends-variability/adjusted-homogenized-canadian-data/surface-air-temperature-access.html) |[Open Goverement Licence - Canada](https://open.canada.ca/en/open-government-licence-canada) |
|Climate change and data| Trends in human behaviour (pre and post industrial revolution | [Hyde](https://themasites.pbl.nl/tridion/en/themasites/hyde/index.html) site [data](https://dataportaal.pbl.nl/downloads/HYDE/) |[creative commons 3.0](https://creativecommons.org/licenses/by/3.0/) |
|Ocean monitoring | Impact of (micro)plastics on marine wildlife | [Hudson River Herring Stomach Contents](https://data.mendeley.com/datasets/s45rhrs5cf/1) | [creative commons 4.0](https://creativecommons.org/licenses/by/4.0/) |
|Ocean monitoring | Impact of industrial fishing practices on marine wildlife | [Alaska Sea Shelf Groundfish Trawl Survey](https://www.fisheries.noaa.gov/resource/data/1982-2018-northern-bering-sea-shelf-groundfish-bottom-trawl-survey-data) | [open for non-commercial, scientific and educational uses](https://www.fisheries.noaa.gov/website-policies-and-disclaimers#copyright-policy) |
|Ocean monitoring | Changes in population size, behavioural patters of a given species | [grey reef shark movements](http://oceantrackingnetwork.org/trackathon/data-sets/) | [open - but must inform OTN of data products created](https://members.oceantrack.org/data/policies/) |
|Citizen participation | Demographics of voters, involvement trends | [Electoral Districts for the 2015 AB election](https://open.alberta.ca/dataset/alberta-provincial-electoral-division-profiles-2010-boundaries-2016-census-data) and [2016 Census information](https://open.alberta.ca/opendata/2015-general-election-results) | Open Goverement Licence - Alberta |
|Citizen participation | Visualizing and interpreting data on budget and expenses | [Federal Budget Data Sets](https://open.canada.ca/data/en/dataset/a35cf382-690c-4221-a971-cf0fd189a46f)| Open Goverment Licence - Canada |
|Citizen participation | Public involvement in policy | [2018 BC Election Referendum Results](https://catalogue.data.gov.bc.ca/dataset/2018-referendum-voting-results)  | Elections BC Open Data Licence |
|Socio economic status and life quality | COVID-19 impact in marginalized groups |[Canadian Confirmed Case details](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310078101) | Open Goverement Licence - Canada |
|Socio economic status and life quality | Income and educational attainment | [Labour market outcomes of postsecondary garduates](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3710018801&pickMembers%5B0%5D=1.1&pickMembers%5B1%5D=4.1&pickMembers%5B2%5D=5.1) | Open Goverement Licence - Canada |
|Socio economic status and life quality | Income and health outcomes | [World Bank Open Data](https://data.worldbank.org) | Open Data |
|Socio economic status and life quality | Geographic distribution of access to services like education and internet in Canada | [National Broadband Data](https://open.canada.ca/data/en/dataset/00a331db-121b-445d-b119-35dbbe3eedd9)| Open Goverement Licence - Canada |
