### ISSUE TITLE
Issue of Issues

### ISSUE THREAD

**Issue by ghost** [callysto/hackathon#34]
# Welcome to JupyterCon2020 Callysto Sprint Session!

## Summary

In this issue you can find links to all tasks. 

Project management tool https://github.com/callysto/hackathon/projects/1 

Team lead @lgfunderburk 
Maintainer @byrcyb 
Mentors @misterhay @mlamoureux  @BryceHaley 

If you have any questions about the project, email contact@callysto.ca. 

## Sprint Summary

Click the video below to learn more about our sprint:

[![](http://img.youtube.com/vi/M2vOv11p_j8/0.jpg)](http://www.youtube.com/watch?v=M2vOv11p_j8 "JupyterCon 2020: Callysto Sprint")
 
## Templates, resources and sample notebooks

If you are seeking inspiration, [look here](https://github.com/callysto/hackathon/issues/30).

### Grassroots contributor

Pick this option if you'd prefer to work on a notebook from scratch. 

[1. Select a topic you like from this list.](https://github.com/callysto/hackathon/issues/26)

[2. Identify open data sets relevant to the topic you found.](https://github.com/callysto/hackathon/issues/27)

[3. Develop a Python script that can download and load the data into a Jupyter notebook.](https://github.com/callysto/hackathon/issues/28)

[4. Develop a Jupyter notebook exploring the dataset, and questions you are interested in](https://github.com/callysto/hackathon/issues/29). 

[5. Create user interfaces that allow users to easily create multiple visualizations.](https://github.com/callysto/hackathon/issues/33)

[Remember to incorporate your work into this repository. ](https://github.com/callysto/hackathon/issues/31)

[Let us know how you prefer we give you credit.](https://github.com/callysto/hackathon/issues/32)

### Data Ambassador

Pick this task if you'd prefer to focus on bridging the gap between members with a technical and a non-technical background. The task can either be focused on language (interpretation of results), or infrastructure (deploying a set of notebooks offline). 

The main tasks involved in being a Data Ambassador:

1. [Help us identify solutions that allow offline access to Jupyter notebooks.](https://github.com/callysto/hackathon/issues/36)

2. [Help us create YouTube videos and content whose focus is on interpreting data. Notebooks provided.](https://github.com/callysto/hackathon/issues/37)

[Remember to incorporate your work into this repository. ](https://github.com/callysto/hackathon/issues/31)

[Let us know how you prefer we give you credit.](https://github.com/callysto/hackathon/issues/32)

### Perfectionist
Pick this option if you'd prefer to focus on perfecting specific aspects of an existing notebook that visualizes data. These aspects include, but are not limited to commenting on visualizations, changing wording within notebooks, improving functionality of notebooks.

Here are the main repositories where we keep our work:

Notebooks on sustainability https://github.com/callysto/math-sustainability-case-studies 

Lesson plans https://github.com/callysto/lesson-plans 

Curriculum notebooks https://github.com/callysto/curriculum-notebooks 

Hackathon notebooks https://github.com/callysto/hackathon

Please [fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) the repository (or repositories), and create a pull request to propose your changes.

[Let us know how you prefer we give you credit.](https://github.com/callysto/hackathon/issues/32)

**Comment by BryceHaley** [comment]
test comment
