### ISSUE TITLE
Deploy Jupyter Notebooks Offline

### ISSUE THREAD

**Issue by ghost** [callysto/hackathon#36]
One of the challenges Callysto faces is supporting students who don't have access to internet. 

Our platform is currently accessible provided the student has internet. 

Why not install locally? Well, part of the point of having an online platform was to remove the need to install Anaconda, Python3, and the right version of all the dependencies we use in our notebooks. 

The online [Callysto Hub](https://hub.callysto.ca/) is ready to launch all of our notebooks https://callysto.ca/learning_modules/ 

But what if a student has limited to no access to internet? 

The challenge is proposing different technologies that:

1. Ease as much as possible the need to install software and dependencies

2. Are deployable offline

3. Are compatible with Windows, MacOS and Linux/Ubuntu operating systems. 

A few solutions include:

- Setting up a Docker container (and packaging in a user-friendly manner)
- Packaging everything into a tar file that can be saved on a USB 
- Developing an executable script that allows for easy installation (command line tool, or user interface). The executable file installs Python3, Jupyter notebook, clones our repositories, and installs the adequate versions for dependencies used in our notebooks. 

Your task is helping us identify technologies, scripts, and open source tools that would allow us to provide our material to students who have limited to no access to internet.

Create a google doc (and share a link in the comments) with ideas, projects that tackle this issue, initiatives, etc. 

If you have code or collaborate with someone who does this, please point us to the GitHub repo along with a link to any licenses used. You are welcome to collaborate with us on a solution from scratch. Please indicate if this is something you are interested in.

**Comment by ghost** [comment]
Voila documentation https://github.com/voila-dashboards/voila 
https://voila.readthedocs.io/en/latest/customize.html 
Can deploy offline 
Explore this feature

**Comment by annefou** [comment]
Awesome! We are in a different timezone but I really would love to follow up on this and collaborate on this issue.

**Comment by misterhay** [comment]
Quite a few Callysto notebooks pull data from online sources, usually CSV files, it would be good to have a mechanism for finding all of those and caching them for offline use somehow. Without having to rewrite the notebooks and store the CSV files on GitHub.

It looks like the likely notebooks are:

'./EnglishLanguageArts/PartsOfSpeech/parts-of-speech.ipynb',
 './EnglishLanguageArts/ReadabilityStatistics/readability-statistics.ipynb',
 './EnglishLanguageArts/ShakespeareStatistics/shakespeare-and-statistics.ipynb',
 './Health/CALM/CALM-moving-out-2.ipynb',
 './Health/CALM/CALM-moving-out.ipynb',
 './Mathematics/BudgetAndBankingAssignment/budget-and-banking-assignment.ipynb',
 './Mathematics/CentralTendency/central-tendency.ipynb',
 './Mathematics/CentralTendencyAndOutlier/outliers-and-central-tendency.ipynb',
 './Mathematics/CurveFitting/curve-fitting-data.ipynb',
 './Mathematics/StatisticalReasoning/statistical-reasoning.ipynb',
 './Mathematics/StatisticsProject/AccessingData/climate-monthly.ipynb',
 './Mathematics/StatisticsProject/AccessingData/fruit-tree-popularity.ipynb',
 './Mathematics/StatisticsProject/AccessingData/gapminder.ipynb',
 './Mathematics/StatisticsProject/AccessingData/google-ngram-viewer.ipynb',
 './Mathematics/StatisticsProject/AccessingData/library-indicators.ipynb',
 './Mathematics/StatisticsProject/AccessingData/mapping-tree-locations.ipynb',
 './Mathematics/StatisticsProject/AccessingData/movie-theatre-releases.ipynb',
 './Mathematics/StatisticsProject/AccessingData/nba.ipynb',
 './Mathematics/StatisticsProject/AccessingData/nhl.ipynb',
 './Mathematics/StatisticsProject/AccessingData/olympics.ipynb',
 './Mathematics/StatisticsProject/AccessingData/pet-popularity.ipynb',
 './Mathematics/StatisticsProject/AccessingData/spotify-popularity.ipynb',
 './Mathematics/StatisticsProject/AccessingData/weather-hourly-canada.ipynb',
 './Mathematics/StatisticsProject/AccessingData/wikipedia-mars-missions.ipynb',
 './Mathematics/StatisticsProject/example-project-income-per-person.ipynb',
 './Science/ClimateChange/climate-change.ipynb',
 './Science/Climatograph/climatograph.ipynb',
 './Science/ElectricityConsumptionMonitoring/electricity-consumption-monitoring.ipynb',
 './Science/NewtonsFirstLaw/newtons-first-law.ipynb',
 './Science/NuclearDecay/nuclear-decay.ipynb',
 './Science/SourcesOfEnergy/resources-and-recycling.ipynb',
 './SocialStudies/GeographyAmericanRevolution/geographic-progression-american-revolution.ipynb',
 './SocialStudies/GeographyResidentialSchools/geography-of-residential-schools.ipynb',
 './SocialStudies/Globalization/communication-and-globalization.ipynb',
 './SocialStudies/Globalization/languages-an-important-identity-in-globalizing-world.ipynb',
 './SocialStudies/Globalization/migration-necessity-for-diversity.ipynb',
 './SocialStudies/Globalization/music-is-ubiquitous.ipynb',
 './SocialStudies/Globalization/sustainability-a-side-effect-of-globalization.ipynb',
 './SocialStudies/Globalization/trade-and-globalization.ipynb',
 './TechnologyStudies/ComputerScienceSocrata/1-introduction-to-socrata-and-soda.ipynb',
 './TechnologyStudies/ComputerScienceSocrata/2-introduction-to-plotly.ipynb',
 './TechnologyStudies/ComputerScienceSocrata/3-joining-datasets.ipynb',
 './TechnologyStudies/ComputerScienceSocrata/4-filtering-datasets.ipynb'
