### ISSUE TITLE
How to interpret data?

### ISSUE THREAD

**Issue by ghost** [callysto/hackathon#37]
The task is to create either YouTube, audio or written content whose focus is on how to interpret graphs. 

You can use any of the following resources to help you guide your content. You will need a Google or Microsoft account to access any of our Jupyter notebooks.

### Callysto Jupyter Notebooks

- Visualizing COVID-19 total number of cases around the world: [Click here to launch](http://tinyurl.com/y2mqyc27)

- Labour force characteristics by Indigenous group and educational attainment (2007 - 2019): [Click here to launch](http://tinyurl.com/y7x7nwz9)

- COVID-19 math model [Click here to launch](http://tinyurl.com/y5m8auk9)

### From JupyterCon2020

Covid19 Dashboard https://covid19dashboards.com/ 

### Statistics Canada and Gapminder

- Statistics Canada, Physical flow account for greenhouse gas emissions: Interactive tool https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2020008-eng.htm 

- Gapminder offline tools https://www.gapminder.org/tools-offline/ 

The goal is to use the graphs generated in the notebooks and resources above to guide students through the process of reading and interpreting a graph. 

Suggested outline:

1. What are graphs

2. How can we use graphs

3. What does it mean to interpret a graph

4. Example of interpreting a graph (use any of the resources above)

Target audience: students in grades 7 and above (see [here for details on the grade system in Canada](https://en.wikipedia.org/wiki/Education_in_Canada#Levels_in_education)). 

Recommendations: avoid jargon as much as possible, use simple words. Assume people have little to no technical or domain expertise.

**Comment by byrcyb** [comment]
I'm going to close this issue as some of our notebook links are pointing to github repositories that are not yet easily accessible to our learners. Once we determine where we should migrate the content, we can revisit.
