### ISSUE TITLE
Books Introduction: Alice's Adventures in Wonderland Sugguestions 

### ISSUE THREAD

**Issue by mgrant46** [callysto/hackathon#46]
https://github.com/callysto/hackathon/blob/notebooks-update/HackathonNotebooks/Books/books-intro.ipynb

WOW great start! It is an inspiration for other hackathon content. Here are a few suggestions for the this first notebook.  

- [x] Chapter Lengths Visualization- Maybe prompt the them to see to the comparison of character count to a story structure. Does it look similar, why or why not. Like this one? Character count vs word count , character count works better with this correlation. https://www.researchgate.net/profile/Sara-Elshafie/publication/326720118/figure/fig1/AS:926468729208833@1597898766646/Freytags-pyramid-also-known-as-the-dramatic-arc-showing-a-five-part-story.png
- [x] Adjective, verbs, nouns and proper nouns. It would be nice to see a quick visual on the definitions. Rather than just a link. I created this if you want to share it. https://drive.google.com/drive/folders/1rCUHnGi5Lq-tjqh4bK4eRuqUYVHSFM5P?usp=sharing

**Comment by misterhay** [comment]
Great ideas, thank you.
