### ISSUE TITLE
Breaking code and breaking down the code required fixes 

### ISSUE THREAD

**Issue by mgrant46** [callysto/hackathon#47]
https://github.com/callysto/curiosity-hackathon/blob/main/learning-code-soccer.ipynb

This notebook is from this page https://callysto-hackathon.netlify.app/chapter4#1. "Start Here" step 2.  It is a very engaging and helpful notebook. It provides explicit instructions and gets the user to troubleshoot. The video flows nicely with the notebook. In saying that, it requires some python fixes by the user. 

- [x] The link on the webpage does not go to the current "Fixed" notebook. https://callysto-hackathon.netlify.app/chapter4#1
- [x] Make sure the saved notebook has the outputs cleared, as the current saved version does not.

**Comment by byrcyb** [comment]
I checked the notebook and link works and notebook has outputs cleared. I think this is good to close.
